# Generated by Django 3.0.5 on 2021-11-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20211104_0457'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe_Ingredient',
            new_name='RecipeIngredient',
        ),
    ]
